/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.KhieuNaiView;

import Model.ModelKhieuNai;
import Model.ModelTaiKhoan;
import com.formdev.flatlaf.FlatClientProperties;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.UUID;
import raven.toast.Notifications;

/**
 *
 * @author ADMIN
 */
public class CheckKhieuNai extends javax.swing.JPanel {
    private ModelKhieuNai khieuNai;
    private ModelTaiKhoan taiKhoan;
    /**
     * Creates new form CheckKhieuNai
     */
    public CheckKhieuNai(ModelKhieuNai khieuNai) {
        this.khieuNai = khieuNai;
        initComponents();
        txtTieuDe.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold +2;");
        loadData(khieuNai);
    }
    private void loadData(ModelKhieuNai data){
        if (data != null) {
            txtHoTen.setText(data.getHoTen());
            txtPhanLoai.setText(data.getPhanLoai());
            txtTieuDe.setText(data.getTieuDe());
            DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            txtNgayGui.setText(df.format(data.getNgayGui()));
            if (data.getNgayDuyet()!=null) txtNgayDuyet.setText(df.format(data.getNgayDuyet()));
            txtNoiDung.setText(data.getNoiDung());
            txtHoiDap.setText(data.getHoiDap());
        }
    }
    
    public ModelKhieuNai getData() {
        // Continue gathering other data
        String hoTen = txtHoTen.getText().trim();
        Date ngayGui = new Date(System.currentTimeMillis());
        String phanLoai = txtPhanLoai.getText();
        String tieuDe = txtTieuDe.getText();
        String noiDung = txtNoiDung.getText();
        String hoiDap = txtHoiDap.getText();
        return new ModelKhieuNai(UUID.randomUUID().toString(), hoTen, phanLoai, tieuDe, noiDung, hoiDap, "Chưa duyệt", ngayGui, new Date(System.currentTimeMillis()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTieuDe = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHoiDap = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtNgayGui = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNgayDuyet = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPhanLoai = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();

        jLabel1.setText("Họ tên:");

        txtHoTen.setText("Tự động nhá");

        jLabel3.setText("Tiêu đề:");

        jLabel4.setText("Nội dung");

        txtTieuDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTieuDe.setText("jLabel5");

        jLabel7.setText("Hồi đáp");

        txtHoiDap.setColumns(20);
        txtHoiDap.setLineWrap(true);
        txtHoiDap.setTabSize(16);
        txtHoiDap.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtHoiDap);

        jLabel8.setText("Ngày gửi:");

        txtNgayGui.setText("jLabel9");

        jLabel10.setText("Ngày duyệt:");

        txtNgayDuyet.setText("Chưa duyệt");

        jLabel12.setText("Phân loại:");

        txtPhanLoai.setText("Khiếu nại");

        txtNoiDung.setEditable(false);
        txtNoiDung.setColumns(20);
        txtNoiDung.setLineWrap(true);
        txtNoiDung.setRows(5);
        txtNoiDung.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtNoiDung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayGui, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTieuDe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayGui))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNgayDuyet))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel txtHoTen;
    private javax.swing.JTextArea txtHoiDap;
    private javax.swing.JLabel txtNgayDuyet;
    private javax.swing.JLabel txtNgayGui;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JLabel txtPhanLoai;
    private javax.swing.JLabel txtTieuDe;
    // End of variables declaration//GEN-END:variables
}
