/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.KhieuNaiView;

import View.HomeView.Card.CardModel;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class KhieuNaiCard extends javax.swing.JPanel {

    /**
     * Creates new form KhieuNaiCard
     */
    public KhieuNaiCard() {
        initComponents();
        setOpaque(false);
        URL approveUrl = getClass().getResource("/images/approve.png");
        URL dismissUrl = getClass().getResource("/images/dismiss.png");
        URL pendingUrl = getClass().getResource("/images/pending.png");
        try (Connection conn = Database.DatabaseConnection.getConnection();
            Statement stmt = conn.createStatement()) {

           // Truy vấn dữ liệu
           String daDuyet = "SELECT COUNT(*) AS approve FROM khieu_nai WHERE xetDuyet = 'Đã duyệt'";
           String tuChoi = "SELECT COUNT(*) AS dismiss FROM khieu_nai WHERE xetDuyet = 'Từ chối'";
           String dangCho = "SELECT COUNT(*) AS pending FROM khieu_nai WHERE xetDuyet = 'Chờ duyệt'";

           int approve = 0, dismiss = 0, pending = 0;

           // Lấy dữ liệu
           ResultSet rsTongDaDuyet = stmt.executeQuery(daDuyet);
           if (rsTongDaDuyet.next()) approve = rsTongDaDuyet.getInt("approve");

           ResultSet rsTongChuaDuyet = stmt.executeQuery(tuChoi);
           if (rsTongChuaDuyet.next()) dismiss = rsTongChuaDuyet.getInt("dismiss");

           ResultSet rsTongCho = stmt.executeQuery(dangCho);
           if (rsTongCho.next()) pending = rsTongCho.getInt("pending");


           // Cập nhật dữ liệu lên các CardPanel
           if (approveUrl != null && pendingUrl != null && dismissUrl != null) {
               cardPanel3.setData(new CardModel(new ImageIcon(approveUrl), "Đã xử lý", approve+""));
               cardPanel2.setData(new CardModel(new ImageIcon(pendingUrl), "Chờ duyệt", pending+""));
               cardPanel1.setData(new CardModel(new ImageIcon(dismissUrl), "Đã từ chối", dismiss+""));
           } else {
               System.out.println("Không tìm thấy một hoặc nhiều hình ảnh.");
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel1 = new View.HomeView.Card.CardPanel();
        cardPanel2 = new View.HomeView.Card.CardPanel();
        cardPanel3 = new View.HomeView.Card.CardPanel();

        cardPanel1.setColor1(new java.awt.Color(17, 153, 142));
        cardPanel1.setColor2(new java.awt.Color(56, 239, 125));

        cardPanel2.setColor1(new java.awt.Color(238, 205, 163));
        cardPanel2.setColor2(new java.awt.Color(239, 98, 159));

        cardPanel3.setColor1(new java.awt.Color(248, 87, 166));
        cardPanel3.setColor2(new java.awt.Color(255, 114, 97));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cardPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cardPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.HomeView.Card.CardPanel cardPanel1;
    private View.HomeView.Card.CardPanel cardPanel2;
    private View.HomeView.Card.CardPanel cardPanel3;
    // End of variables declaration//GEN-END:variables
}
